/* tslint:disable */
/* eslint-disable */
/**
 * Great Man API
 * great man api
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@astrack.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNewManRequestManInfosInner
 */
export interface CreateNewManRequestManInfosInner {
    /**
     * 
     * @type {string}
     * @memberof CreateNewManRequestManInfosInner
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNewManRequestManInfosInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNewManRequestManInfosInner
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the CreateNewManRequestManInfosInner interface.
 */
export function instanceOfCreateNewManRequestManInfosInner(value: object): value is CreateNewManRequestManInfosInner {
    return true;
}

export function CreateNewManRequestManInfosInnerFromJSON(json: any): CreateNewManRequestManInfosInner {
    return CreateNewManRequestManInfosInnerFromJSONTyped(json, false);
}

export function CreateNewManRequestManInfosInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNewManRequestManInfosInner {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'] == null ? undefined : json['language'],
        'name': json['name'] == null ? undefined : json['name'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function CreateNewManRequestManInfosInnerToJSON(value?: CreateNewManRequestManInfosInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'language': value['language'],
        'name': value['name'],
        'comment': value['comment'],
    };
}

