/* tslint:disable */
/* eslint-disable */
/**
 * Great Man API
 * great man api
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@astrack.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateNewManRequestManInfosInner } from './CreateNewManRequestManInfosInner';
import {
    CreateNewManRequestManInfosInnerFromJSON,
    CreateNewManRequestManInfosInnerFromJSONTyped,
    CreateNewManRequestManInfosInnerToJSON,
} from './CreateNewManRequestManInfosInner';

/**
 * 
 * @export
 * @interface CreateNewManRequest
 */
export interface CreateNewManRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNewManRequest
     */
    headImgUrl?: string | null;
    /**
     * 
     * @type {Array<CreateNewManRequestManInfosInner>}
     * @memberof CreateNewManRequest
     */
    manInfos?: Array<CreateNewManRequestManInfosInner>;
}

/**
 * Check if a given object implements the CreateNewManRequest interface.
 */
export function instanceOfCreateNewManRequest(value: object): value is CreateNewManRequest {
    return true;
}

export function CreateNewManRequestFromJSON(json: any): CreateNewManRequest {
    return CreateNewManRequestFromJSONTyped(json, false);
}

export function CreateNewManRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNewManRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'headImgUrl': json['headImgUrl'] == null ? undefined : json['headImgUrl'],
        'manInfos': json['manInfos'] == null ? undefined : ((json['manInfos'] as Array<any>).map(CreateNewManRequestManInfosInnerFromJSON)),
    };
}

export function CreateNewManRequestToJSON(value?: CreateNewManRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'headImgUrl': value['headImgUrl'],
        'manInfos': value['manInfos'] == null ? undefined : ((value['manInfos'] as Array<any>).map(CreateNewManRequestManInfosInnerToJSON)),
    };
}

