/* tslint:disable */
/* eslint-disable */
/**
 * Great Man API
 * great man api
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@astrack.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMan200Response
 */
export interface GetMan200Response {
    /**
     * 姓名
     * @type {string}
     * @memberof GetMan200Response
     */
    name?: string;
    /**
     * 评论
     * @type {string}
     * @memberof GetMan200Response
     */
    comment?: string | null;
    /**
     * 头图
     * @type {string}
     * @memberof GetMan200Response
     */
    headImgUrl?: string | null;
}

/**
 * Check if a given object implements the GetMan200Response interface.
 */
export function instanceOfGetMan200Response(value: object): value is GetMan200Response {
    return true;
}

export function GetMan200ResponseFromJSON(json: any): GetMan200Response {
    return GetMan200ResponseFromJSONTyped(json, false);
}

export function GetMan200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMan200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'headImgUrl': json['headImgUrl'] == null ? undefined : json['headImgUrl'],
    };
}

export function GetMan200ResponseToJSON(value?: GetMan200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'comment': value['comment'],
        'headImgUrl': value['headImgUrl'],
    };
}

