/* tslint:disable */
/* eslint-disable */
/**
 * Great Man API
 * great man api
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@astrack.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTalks200ResponseInner
 */
export interface GetTalks200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetTalks200ResponseInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetTalks200ResponseInner
     */
    title?: string;
    /**
     * 创建日期
     * @type {Date}
     * @memberof GetTalks200ResponseInner
     */
    date?: Date;
}

/**
 * Check if a given object implements the GetTalks200ResponseInner interface.
 */
export function instanceOfGetTalks200ResponseInner(value: object): value is GetTalks200ResponseInner {
    return true;
}

export function GetTalks200ResponseInnerFromJSON(json: any): GetTalks200ResponseInner {
    return GetTalks200ResponseInnerFromJSONTyped(json, false);
}

export function GetTalks200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTalks200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
    };
}

export function GetTalks200ResponseInnerToJSON(value?: GetTalks200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
    };
}

