/* tslint:disable */
/* eslint-disable */
/**
 * Great Man API
 * great man api
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@astrack.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TalkAttachmentsInner
 */
export interface TalkAttachmentsInner {
    /**
     * 
     * @type {string}
     * @memberof TalkAttachmentsInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof TalkAttachmentsInner
     */
    value?: string;
}

/**
 * Check if a given object implements the TalkAttachmentsInner interface.
 */
export function instanceOfTalkAttachmentsInner(value: object): value is TalkAttachmentsInner {
    return true;
}

export function TalkAttachmentsInnerFromJSON(json: any): TalkAttachmentsInner {
    return TalkAttachmentsInnerFromJSONTyped(json, false);
}

export function TalkAttachmentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TalkAttachmentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function TalkAttachmentsInnerToJSON(value?: TalkAttachmentsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

