/* tslint:disable */
/* eslint-disable */
/**
 * Great Man API
 * great man api
 *
 * The version of the OpenAPI document: 1.0
 * Contact: admin@astrack.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TalkTalkContentsInner
 */
export interface TalkTalkContentsInner {
    /**
     * 
     * @type {string}
     * @memberof TalkTalkContentsInner
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof TalkTalkContentsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TalkTalkContentsInner
     */
    mainBody?: string;
    /**
     * 
     * @type {string}
     * @memberof TalkTalkContentsInner
     */
    interviwer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TalkTalkContentsInner
     */
    source?: string | null;
}

/**
 * Check if a given object implements the TalkTalkContentsInner interface.
 */
export function instanceOfTalkTalkContentsInner(value: object): value is TalkTalkContentsInner {
    return true;
}

export function TalkTalkContentsInnerFromJSON(json: any): TalkTalkContentsInner {
    return TalkTalkContentsInnerFromJSONTyped(json, false);
}

export function TalkTalkContentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TalkTalkContentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'] == null ? undefined : json['language'],
        'title': json['title'] == null ? undefined : json['title'],
        'mainBody': json['mainBody'] == null ? undefined : json['mainBody'],
        'interviwer': json['interviwer'] == null ? undefined : json['interviwer'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function TalkTalkContentsInnerToJSON(value?: TalkTalkContentsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'language': value['language'],
        'title': value['title'],
        'mainBody': value['mainBody'],
        'interviwer': value['interviwer'],
        'source': value['source'],
    };
}

